"""Add keyframe column to bilibili_live_rooms

Revision ID: 89cb0f5ed20c
Revises: 
Create Date: 2025-03-24 10:52:09.012755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89cb0f5ed20c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('bilibili_gu_room_id_9fb587_idx', table_name='bilibili_guard_info')
    op.drop_index('bilibili_gu_room_id_c22ed9_idx', table_name='bilibili_guard_info')
    op.drop_index('bilibili_gu_room_id_ecbb36_idx', table_name='bilibili_guard_info')
    op.drop_index('bilibili_gu_ruid_5bccf6_idx', table_name='bilibili_guard_info')
    op.drop_index('bilibili_gu_timesta_df6cce_idx', table_name='bilibili_guard_info')
    op.drop_index('bilibili_gu_total_g_0d323d_idx', table_name='bilibili_guard_info')
    op.drop_table('bilibili_guard_info')
    op.drop_index('bilibili_gu_room_id_a8b7c2_idx', table_name='bilibili_guard_history')
    op.drop_index('bilibili_gu_room_id_e4d787_idx', table_name='bilibili_guard_history')
    op.drop_index('bilibili_gu_ruid_aa35fc_idx', table_name='bilibili_guard_history')
    op.drop_index('bilibili_gu_timesta_297606_idx', table_name='bilibili_guard_history')
    op.drop_index('bilibili_gu_uid_14edb8_idx', table_name='bilibili_guard_history')
    op.drop_table('bilibili_guard_history')
    op.drop_index('bilibili_gu_guard_l_60282b_idx', table_name='bilibili_guards')
    op.drop_index('bilibili_gu_rank_58e87b_idx', table_name='bilibili_guards')
    op.drop_index('bilibili_gu_room_id_0b1cf9_idx', table_name='bilibili_guards')
    op.drop_index('bilibili_gu_ruid_fdddbc_idx', table_name='bilibili_guards')
    op.drop_index('bilibili_gu_timesta_685eaa_idx', table_name='bilibili_guards')
    op.drop_index('bilibili_gu_uid_964fcb_idx', table_name='bilibili_guards')
    op.drop_index('bilibili_guards_guard_info_id_46fade78', table_name='bilibili_guards')
    op.drop_table('bilibili_guards')
    op.drop_table('bilibili_medal_colors')
    op.drop_index('auth_group_name_a6ea08ec_like', table_name='auth_group')
    op.drop_table('auth_group')
    op.drop_index('bilibili_us_current_a59213_idx', table_name='bilibili_users')
    op.drop_index('bilibili_us_current_b837ae_idx', table_name='bilibili_users')
    op.drop_index('bilibili_us_guard_l_0b02af_idx', table_name='bilibili_users')
    op.drop_index('bilibili_us_wealth__e770cc_idx', table_name='bilibili_users')
    op.drop_table('bilibili_users')
    op.drop_index('auth_user_groups_group_id_97559544', table_name='auth_user_groups')
    op.drop_index('auth_user_groups_user_id_6a12ed8b', table_name='auth_user_groups')
    op.drop_table('auth_user_groups')
    op.drop_index('django_admin_log_content_type_id_c4bce8eb', table_name='django_admin_log')
    op.drop_index('django_admin_log_user_id_c564eba6', table_name='django_admin_log')
    op.drop_table('django_admin_log')
    op.drop_index('bilibili_me_name_a2bc28_idx', table_name='bilibili_medals')
    op.drop_index('bilibili_me_target__58347d_idx', table_name='bilibili_medals')
    op.drop_table('bilibili_medals')
    op.drop_index('bilibili_co_count_5ccb9f_idx', table_name='bilibili_contribution_info')
    op.drop_index('bilibili_co_room_id_0485a2_idx', table_name='bilibili_contribution_info')
    op.drop_index('bilibili_co_room_id_925713_idx', table_name='bilibili_contribution_info')
    op.drop_index('bilibili_co_room_id_dc9d4a_idx', table_name='bilibili_contribution_info')
    op.drop_index('bilibili_co_ruid_4b6c90_idx', table_name='bilibili_contribution_info')
    op.drop_index('bilibili_co_timesta_8f1a1e_idx', table_name='bilibili_contribution_info')
    op.drop_table('bilibili_contribution_info')
    op.drop_index('bilibili_co_medal_l_b99be5_idx', table_name='bilibili_contributions')
    op.drop_index('bilibili_co_rank_71604e_idx', table_name='bilibili_contributions')
    op.drop_index('bilibili_co_room_id_c0c091_idx', table_name='bilibili_contributions')
    op.drop_index('bilibili_co_ruid_926b86_idx', table_name='bilibili_contributions')
    op.drop_index('bilibili_co_timesta_2da33f_idx', table_name='bilibili_contributions')
    op.drop_index('bilibili_contributions_contribution_info_id_adeecf68', table_name='bilibili_contributions')
    op.drop_index('bilibili_contributions_medal_id_da496882', table_name='bilibili_contributions')
    op.drop_index('bilibili_contributions_user_id_064f5076', table_name='bilibili_contributions')
    op.drop_table('bilibili_contributions')
    op.drop_table('django_migrations')
    op.drop_index('bilibili_co_room_id_513917_idx', table_name='bilibili_contribution_history')
    op.drop_index('bilibili_co_ruid_7593f5_idx', table_name='bilibili_contribution_history')
    op.drop_index('bilibili_co_timesta_ea91c1_idx', table_name='bilibili_contribution_history')
    op.drop_index('bilibili_co_uid_fa94cf_idx', table_name='bilibili_contribution_history')
    op.drop_index('bilibili_co_wealth__271377_idx', table_name='bilibili_contribution_history')
    op.drop_table('bilibili_contribution_history')
    op.drop_table('django_content_type')
    op.drop_index('django_session_expire_date_a5c62663', table_name='django_session')
    op.drop_index('django_session_session_key_c0390e0f_like', table_name='django_session')
    op.drop_table('django_session')
    op.drop_index('auth_user_user_permissions_permission_id_1fbb5f2c', table_name='auth_user_user_permissions')
    op.drop_index('auth_user_user_permissions_user_id_a95ead1b', table_name='auth_user_user_permissions')
    op.drop_table('auth_user_user_permissions')
    op.drop_index('auth_permission_content_type_id_2f476e4b', table_name='auth_permission')
    op.drop_table('auth_permission')
    op.drop_index('bilibili_li_room_id_ce6bfe_idx', table_name='bilibili_live_room_history')
    op.drop_index('bilibili_li_timesta_e5de94_idx', table_name='bilibili_live_room_history')
    op.drop_index('bilibili_live_room_history_room_id_2f6569db', table_name='bilibili_live_room_history')
    op.drop_table('bilibili_live_room_history')
    op.drop_index('auth_user_username_6821ab7c_like', table_name='auth_user')
    op.drop_table('auth_user')
    op.drop_index('auth_group_permissions_group_id_b120cbf9', table_name='auth_group_permissions')
    op.drop_index('auth_group_permissions_permission_id_84c5c92e', table_name='auth_group_permissions')
    op.drop_table('auth_group_permissions')
    op.add_column('bilibili_live_rooms', sa.Column('keyframe', sa.Text(), nullable=True))
    op.create_index(op.f('ix_bilibili_live_rooms_room_id'), 'bilibili_live_rooms', ['room_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bilibili_live_rooms_room_id'), table_name='bilibili_live_rooms')
    op.drop_column('bilibili_live_rooms', 'keyframe')
    op.create_table('auth_group_permissions',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name='auth_group_permissions_group_id_b120cbf9_fk_auth_group_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name='auth_group_permissio_permission_id_84c5c92e_fk_auth_perm', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='auth_group_permissions_pkey'),
    sa.UniqueConstraint('group_id', 'permission_id', name='auth_group_permissions_group_id_permission_id_0cd325b0_uniq')
    )
    op.create_index('auth_group_permissions_permission_id_84c5c92e', 'auth_group_permissions', ['permission_id'], unique=False)
    op.create_index('auth_group_permissions_group_id_b120cbf9', 'auth_group_permissions', ['group_id'], unique=False)
    op.create_table('auth_user',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('last_login', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=254), autoincrement=False, nullable=False),
    sa.Column('is_staff', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('date_joined', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='auth_user_pkey'),
    sa.UniqueConstraint('username', name='auth_user_username_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('auth_user_username_6821ab7c_like', 'auth_user', ['username'], unique=False)
    op.create_table('bilibili_live_room_history',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('online', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('watched_num', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('watched_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('parent_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('area_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('room_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['bilibili_live_rooms.room_id'], name='bilibili_live_room_h_room_id_2f6569db_fk_bilibili_', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='bilibili_live_room_history_pkey')
    )
    op.create_index('bilibili_live_room_history_room_id_2f6569db', 'bilibili_live_room_history', ['room_id'], unique=False)
    op.create_index('bilibili_li_timesta_e5de94_idx', 'bilibili_live_room_history', ['timestamp'], unique=False)
    op.create_index('bilibili_li_room_id_ce6bfe_idx', 'bilibili_live_room_history', ['room_id'], unique=False)
    op.create_table('auth_permission',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('codename', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='auth_permission_content_type_id_2f476e4b_fk_django_co', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='auth_permission_pkey'),
    sa.UniqueConstraint('content_type_id', 'codename', name='auth_permission_content_type_id_codename_01ab375a_uniq'),
    postgresql_ignore_search_path=False
    )
    op.create_index('auth_permission_content_type_id_2f476e4b', 'auth_permission', ['content_type_id'], unique=False)
    op.create_table('auth_user_user_permissions',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name='auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='auth_user_user_permissions_pkey'),
    sa.UniqueConstraint('user_id', 'permission_id', name='auth_user_user_permissions_user_id_permission_id_14a6b632_uniq')
    )
    op.create_index('auth_user_user_permissions_user_id_a95ead1b', 'auth_user_user_permissions', ['user_id'], unique=False)
    op.create_index('auth_user_user_permissions_permission_id_1fbb5f2c', 'auth_user_user_permissions', ['permission_id'], unique=False)
    op.create_table('django_session',
    sa.Column('session_key', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('session_data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expire_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('session_key', name='django_session_pkey')
    )
    op.create_index('django_session_session_key_c0390e0f_like', 'django_session', ['session_key'], unique=False)
    op.create_index('django_session_expire_date_a5c62663', 'django_session', ['expire_date'], unique=False)
    op.create_table('django_content_type',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('app_label', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='django_content_type_pkey'),
    sa.UniqueConstraint('app_label', 'model', name='django_content_type_app_label_model_76bd3d3b_uniq'),
    postgresql_ignore_search_path=False
    )
    op.create_table('bilibili_contribution_history',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ruid', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('uid', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('rank', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('medal_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('guard_level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('wealth_level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='bilibili_contribution_history_pkey')
    )
    op.create_index('bilibili_co_wealth__271377_idx', 'bilibili_contribution_history', ['wealth_level'], unique=False)
    op.create_index('bilibili_co_uid_fa94cf_idx', 'bilibili_contribution_history', ['uid'], unique=False)
    op.create_index('bilibili_co_timesta_ea91c1_idx', 'bilibili_contribution_history', ['timestamp'], unique=False)
    op.create_index('bilibili_co_ruid_7593f5_idx', 'bilibili_contribution_history', ['ruid'], unique=False)
    op.create_index('bilibili_co_room_id_513917_idx', 'bilibili_contribution_history', ['room_id'], unique=False)
    op.create_table('django_migrations',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('app', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('applied', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='django_migrations_pkey')
    )
    op.create_table('bilibili_contributions',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ruid', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('rank', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('medal_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('medal_is_light', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_mystery', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('icon_show', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('medal_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('contribution_info_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['contribution_info_id'], ['bilibili_contribution_info.id'], name='bilibili_contributio_contribution_info_id_adeecf68_fk_bilibili_', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['medal_id'], ['bilibili_medals.id'], name='bilibili_contributions_medal_id_da496882_fk_bilibili_medals_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['bilibili_users.uid'], name='bilibili_contributions_user_id_064f5076_fk_bilibili_users_uid', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='bilibili_contributions_pkey'),
    sa.UniqueConstraint('room_id', 'user_id', name='unique_contribution_room_user')
    )
    op.create_index('bilibili_contributions_user_id_064f5076', 'bilibili_contributions', ['user_id'], unique=False)
    op.create_index('bilibili_contributions_medal_id_da496882', 'bilibili_contributions', ['medal_id'], unique=False)
    op.create_index('bilibili_contributions_contribution_info_id_adeecf68', 'bilibili_contributions', ['contribution_info_id'], unique=False)
    op.create_index('bilibili_co_timesta_2da33f_idx', 'bilibili_contributions', ['timestamp'], unique=False)
    op.create_index('bilibili_co_ruid_926b86_idx', 'bilibili_contributions', ['ruid'], unique=False)
    op.create_index('bilibili_co_room_id_c0c091_idx', 'bilibili_contributions', ['room_id'], unique=False)
    op.create_index('bilibili_co_rank_71604e_idx', 'bilibili_contributions', ['rank'], unique=False)
    op.create_index('bilibili_co_medal_l_b99be5_idx', 'bilibili_contributions', ['medal_level'], unique=False)
    op.create_table('bilibili_contribution_info',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ruid', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='bilibili_contribution_info_pkey')
    )
    op.create_index('bilibili_co_timesta_8f1a1e_idx', 'bilibili_contribution_info', ['timestamp'], unique=False)
    op.create_index('bilibili_co_ruid_4b6c90_idx', 'bilibili_contribution_info', ['ruid'], unique=False)
    op.create_index('bilibili_co_room_id_dc9d4a_idx', 'bilibili_contribution_info', ['room_id', sa.literal_column('timestamp DESC')], unique=False)
    op.create_index('bilibili_co_room_id_925713_idx', 'bilibili_contribution_info', ['room_id'], unique=False)
    op.create_index('bilibili_co_room_id_0485a2_idx', 'bilibili_contribution_info', ['room_id', 'timestamp'], unique=False)
    op.create_index('bilibili_co_count_5ccb9f_idx', 'bilibili_contribution_info', ['count'], unique=False)
    op.create_table('bilibili_medals',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('target_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('target_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='bilibili_medals_pkey'),
    sa.UniqueConstraint('target_id', name='unique_target_id')
    )
    op.create_index('bilibili_me_target__58347d_idx', 'bilibili_medals', ['target_id'], unique=False)
    op.create_index('bilibili_me_name_a2bc28_idx', 'bilibili_medals', ['name'], unique=False)
    op.create_table('django_admin_log',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('action_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('object_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('object_repr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('action_flag', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('change_message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('action_flag >= 0', name='django_admin_log_action_flag_check'),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='django_admin_log_content_type_id_c4bce8eb_fk_django_co', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='django_admin_log_user_id_c564eba6_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='django_admin_log_pkey')
    )
    op.create_index('django_admin_log_user_id_c564eba6', 'django_admin_log', ['user_id'], unique=False)
    op.create_index('django_admin_log_content_type_id_c4bce8eb', 'django_admin_log', ['content_type_id'], unique=False)
    op.create_table('auth_user_groups',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name='auth_user_groups_group_id_97559544_fk_auth_group_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='auth_user_groups_user_id_6a12ed8b_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='auth_user_groups_pkey'),
    sa.UniqueConstraint('user_id', 'group_id', name='auth_user_groups_user_id_group_id_94350c0c_uniq')
    )
    op.create_index('auth_user_groups_user_id_6a12ed8b', 'auth_user_groups', ['user_id'], unique=False)
    op.create_index('auth_user_groups_group_id_97559544', 'auth_user_groups', ['group_id'], unique=False)
    op.create_table('bilibili_users',
    sa.Column('uid', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('face', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('current_medal_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_medal_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('current_medal_target_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('guard_level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('wealth_level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('uid', name='bilibili_users_pkey')
    )
    op.create_index('bilibili_us_wealth__e770cc_idx', 'bilibili_users', ['wealth_level'], unique=False)
    op.create_index('bilibili_us_guard_l_0b02af_idx', 'bilibili_users', ['guard_level'], unique=False)
    op.create_index('bilibili_us_current_b837ae_idx', 'bilibili_users', ['current_medal_target_id'], unique=False)
    op.create_index('bilibili_us_current_a59213_idx', 'bilibili_users', ['current_medal_level'], unique=False)
    op.create_table('auth_group',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='auth_group_pkey'),
    sa.UniqueConstraint('name', name='auth_group_name_key')
    )
    op.create_index('auth_group_name_a6ea08ec_like', 'auth_group', ['name'], unique=False)
    op.create_table('bilibili_medal_colors',
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('color_start', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('color_end', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('color_border', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('level', name='bilibili_medal_colors_pkey')
    )
    op.create_table('bilibili_guards',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ruid', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('uid', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('rank', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('accompany', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('username', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('face', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name_color', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_mystery', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('medal_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('medal_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('medal_color_start', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('medal_color_end', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('medal_color_border', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('medal_color', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('guard_level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('expired_str', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_top3', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('guard_info_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['guard_info_id'], ['bilibili_guard_info.id'], name='bilibili_guards_guard_info_id_46fade78_fk_bilibili_', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='bilibili_guards_pkey'),
    sa.UniqueConstraint('room_id', 'uid', name='unique_room_user')
    )
    op.create_index('bilibili_guards_guard_info_id_46fade78', 'bilibili_guards', ['guard_info_id'], unique=False)
    op.create_index('bilibili_gu_uid_964fcb_idx', 'bilibili_guards', ['uid'], unique=False)
    op.create_index('bilibili_gu_timesta_685eaa_idx', 'bilibili_guards', ['timestamp'], unique=False)
    op.create_index('bilibili_gu_ruid_fdddbc_idx', 'bilibili_guards', ['ruid'], unique=False)
    op.create_index('bilibili_gu_room_id_0b1cf9_idx', 'bilibili_guards', ['room_id'], unique=False)
    op.create_index('bilibili_gu_rank_58e87b_idx', 'bilibili_guards', ['rank'], unique=False)
    op.create_index('bilibili_gu_guard_l_60282b_idx', 'bilibili_guards', ['guard_level'], unique=False)
    op.create_table('bilibili_guard_history',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ruid', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('uid', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('username', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('rank', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('accompany', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('guard_level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('medal_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='bilibili_guard_history_pkey')
    )
    op.create_index('bilibili_gu_uid_14edb8_idx', 'bilibili_guard_history', ['uid'], unique=False)
    op.create_index('bilibili_gu_timesta_297606_idx', 'bilibili_guard_history', ['timestamp'], unique=False)
    op.create_index('bilibili_gu_ruid_aa35fc_idx', 'bilibili_guard_history', ['ruid'], unique=False)
    op.create_index('bilibili_gu_room_id_e4d787_idx', 'bilibili_guard_history', ['room_id'], unique=False)
    op.create_index('bilibili_gu_room_id_a8b7c2_idx', 'bilibili_guard_history', ['room_id', 'timestamp'], unique=False)
    op.create_table('bilibili_guard_info',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ruid', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('total_guards', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='bilibili_guard_info_pkey')
    )
    op.create_index('bilibili_gu_total_g_0d323d_idx', 'bilibili_guard_info', ['total_guards'], unique=False)
    op.create_index('bilibili_gu_timesta_df6cce_idx', 'bilibili_guard_info', ['timestamp'], unique=False)
    op.create_index('bilibili_gu_ruid_5bccf6_idx', 'bilibili_guard_info', ['ruid'], unique=False)
    op.create_index('bilibili_gu_room_id_ecbb36_idx', 'bilibili_guard_info', ['room_id', 'timestamp'], unique=False)
    op.create_index('bilibili_gu_room_id_c22ed9_idx', 'bilibili_guard_info', ['room_id', sa.literal_column('timestamp DESC')], unique=False)
    op.create_index('bilibili_gu_room_id_9fb587_idx', 'bilibili_guard_info', ['room_id'], unique=False)
    # ### end Alembic commands ###
